### PR TITLE
Some pylint fixes

### PR DESCRIPTION
**Pull request by mdevaev**

### CODE REVIEW

**Comment by flying-sheep** [comment]
the whitespace is there on purpose: it’s not “trailing whitespace”, but indentation: i simply choose to indent empty lines, too, to make code blocks appear more uniform when showing whitespace in an editor.

and the second commit has a misleading message (it would fix #7, not pylint), and makes the code even more opaque. i’ll come up with a prettier fix for #7 myself, OK? :)

**Comment by mdevaev** [comment]
My pylint very worried about the byte, it would be cool if you do it somehow corrected :-)

**Comment by flying-sheep** [comment]
ok, done.

**Comment by mdevaev** [comment]
Thanks! :+1:

**Pull request closed without merging**
